# -*- coding: utf-8 -*-
"""math-quiz-app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EXBxRi9Exl7jILxCzDoZBSqMiOVg8v3z
"""
       
import random
import time

# Ask for player name
name = input("Enter your name: ")

# Ask for difficulty level
level = input("Choose level (easy / medium / hard): ").lower()

# Set number range based on level
if level == "easy":
    min_val, max_val = 1, 10
elif level == "medium":
    min_val, max_val = 10, 50
elif level == "hard":
    min_val, max_val = 50, 100
else:
    print("Invalid level. Defaulting to easy.")
    min_val, max_val = 1, 10

# Initialize score and time
score = 0
start_time = time.time()

# Quiz loop
for i in range(5):
    a = random.randint(min_val, max_val)
    b = random.randint(min_val, max_val)
    answer = int(input(f"What is {a} + {b}? "))

    if answer == a + b:
        print("Correct!")
        score += 1
    else:
        print("Wrong!")
        break

# End time and total time
end_time = time.time()
total_time = round(end_time - start_time, 2)

# Final result
print(f"\n{name}, your score is {score}/5")
print(f"Time taken: {total_time} seconds")

# Save score to file 
with open("score_log.txt", "a") as file:
    file.write(f"{name} scored {score}/5 in {total_time} seconds at {level} level\n")
